In [99]:
import pandas as pd

# df = {
#     'df2': pd.read_csv('../data/kompas_1_2.csv'),
#     'df3': pd.read_csv('../data/raw/kompas_3.csv'),
#     'df4': pd.read_csv('../data/raw/kompas_4.csv'),
#     'df5': pd.read_csv('../data/raw/kompas_5.csv'),
#     'df6': pd.read_csv('../data/raw/kompas_6.csv'),
#     'df7': pd.read_csv('../data/raw/kompas_7.csv'),
#     'df8': pd.read_csv('../data/raw/kompas_8.csv'),
#     'df9': pd.read_csv('../data/raw/kompas_9.csv'),
#     'df10': pd.read_csv('../data/raw/kompas_10.csv'),
#     'df11': pd.read_csv('../data/raw/kompas_11.csv'),
#     'df12': pd.read_csv('../data/raw/kompas_12.csv'),
# }
# df = pd.read_csv('../data/okezone.csv')
# df = {
#     'dfs': pd.read_csv('../data/sindonews.csv'),
#     'df9': pd.read_csv('../data/raw/sindonews_9.csv'),
#     'df10': pd.read_csv('../data/raw/sindonews_10.csv'),
#     'df11': pd.read_csv('../data/raw/sindonews_11.csv'),
#     'df12': pd.read_csv('../data/raw/sindonews_12.csv')
# }
df = {
    'dfs': pd.read_csv('../data/tribunnews.csv'),
    'df3': pd.read_csv('../data/raw/tribunnews_3.csv'),
    'df4': pd.read_csv('../data/raw/tribunnews_4.csv'),
    'df5': pd.read_csv('../data/raw/tribunnews_5.csv'),
    'df6': pd.read_csv('../data/raw/tribunnews_6.csv'),
    'df7': pd.read_csv('../data/raw/tribunnews_7.csv'),
    'df8': pd.read_csv('../data/raw/tribunnews_8.csv'),
    'df9': pd.read_csv('../data/raw/tribunnews_9.csv'),
    'df10': pd.read_csv('../data/raw/tribunnews_10.csv'),
    'df11': pd.read_csv('../data/raw/tribunnews_11.csv'),
    'df12': pd.read_csv('../data/raw/tribunnews_12.csv'),
}

In [100]:
m_to_n = {
    'Jan': '01',
    'Feb': '02',
    'Mar': '03',
    'Apr': '04',
    'Mei': '05',
    'Jun': '06',
    'Jul': '07',
    'Agu': '08',
    'Sep': '09',
    'Okt': '10',
    'Nov': '11',
    'Des': '12',
}
month_to_n = {
    'Januari': '01',
    'Februari': '02',
    'Maret': '03',
    'April': '04',
    'Mei': '05',
    'Juni': '06',
    'Juli': '07',
    'Agustus': '08',
    'September': '09',
    'Oktober': '10',
    'November': '11',
    'Desember': '12',
}

In [101]:
def convert_detik(s):
    d, m, y = s.split(' ')
    m = m_to_n[m]
    y = y if y else '2022'
    return f'{y}-{m}-{d}'
def convert_kompas(s):
    d, m, y = s.split('/')
    return f'{y}-{m}-{d}'
def convert_okezone(s):
    d, m, y = s.split(' ')
    m = month_to_n[m]
    return f'{y}-{m}-{d}'
def convert_sindonews(s):
    d, m, y = s.split(' ')
    m = month_to_n[m]
    return f'{y}-{m}-{d}'
def convert_tribunnews(s):
    d, m, y = s.split(' ')
    m = month_to_n[m]
    return f'{y}-{m}-{d}'
def pad_tribunnews(s):
    y, m, d =s.split('-')
    d = int(d)
    d = f'{d:02}'
    return f'{y}-{m}-{d}'

In [102]:
for i in range(3, 13):
    j = f'df{i}'
    df[j]['date'] = df[j]['date'].apply(convert_sindonews)
    df[j]['date'] = df[j]['date'].apply(pad_tribunnews)
# df['date'] = df['date'].apply(pad_tribunnews)

In [106]:
# df.to_csv('../data/tribunnews.csv', index=False)
dfc = pd.concat(df, ignore_index=True)
dfc

              date                                           headline
0       2022-01-02  Erick Thohir Disebut Sebagai Inspirasi Pelaku ...
1       2022-01-02  Kakorlantas Polri Pastikan Puncak Arus Balik L...
2       2022-01-02  Pelaku Industri Otomotif Antusias Menyambut Ge...
3       2022-01-02  Shin Tae-yong Bilang Striker Indonesia Susah B...
4       2022-01-02  Ini Rekomendasi Terbaru IDAI Soal Pembelajaran...
...            ...                                                ...
232878  2022-12-05  Cara Tak Biasa Kylian Mbappe Jaga Fokus di Pia...
232879  2022-12-05  Live Streaming SCTV, Inggris vs Senegal di Pia...
232880  2022-12-05  Fakta Hasil Prancis vs Polandia di Piala Dunia...
232881  2022-12-05  Cerita Seorang Ibu Gendong Dua Anak dan Bawa D...
232882  2022-12-05  Hasil Prancis vs Polandia 3-1, Mbappe Menggila...

[232883 rows x 2 columns]

In [ ]:
dfc.to_csv('../data/tribunnews.csv', index=False)